### ISSUE TITLE
Support for Quantile(s) Datasketch Post-Aggregators

### ISSUE THREAD

**Issue by Vespira** [level23/druid-client#30]
Hi,

First of all, thanks for your amazing job on this Druid Client !
I'm currently investigating to see what PHP client library we could integrate into our Lumen/Laravel app to query Druid.
I've not tested this one, but so far, from the documentation, and recent updates you seems to be the best candidate.

But I can see that queries implying QuantilesDatasketch are not implemented; and I was wondering if something was currently being under dev or if I could do it myself ?

I forked this lib and currently working on adding Quantile and Quantiles post-aggragators to the solution (with testing ofc).

Question is; should I keep it for my fork, or are you willing to review my PR after I finished ? Should I stop now because you are working on it already ?

Thanks a lot for info,
Alex

**Comment by teyeheimans** [comment]
Hi Alex, sorry for my late reply. Of course we are willing to review your PR. We are not working on it currently.
