### ISSUE TITLE
Can anyone help with how to run raw sql query with this library?

### ISSUE THREAD

**Issue by iamprageeth** [level23/druid-client#36]
Hi,

Thanks for creating this amazing project !
I like to build my raw sql query  using laravel query builder and then get raw query and pass it to druid using this library. Can anyone give me a method to do this?

Thanks.

**Comment by teyeheimans** [comment]
Hi! Sorry for my late reply. Currently there is now way to convert a raw SQL query to a native druid query. However, you can submit the query using the druid web console. If you prefix your query with ` explain plan for <query>`, then you will receive the druid native (json) query as it will be executed. I hope this helps.
