### ISSUE TITLE
Post-aggregations using expressions

### ISSUE THREAD

**Issue by pr-speqta** [level23/druid-client#53]
As per the Druid documentation, there is also the [expression post-aggregator](https://druid.apache.org/docs/latest/querying/post-aggregations/#expression-post-aggregator) available, which I could not find in the package.
* Is there a reason why this was omitted? If not omitted, is there a chance this feature will be added?
* Is there another way to get this type of aggregator working on the v2.0.5 other than by overriding the package classes?

**Comment by teyeheimans** [comment]
Hi @pr-speqta , you are totally correct. We have added it now! It is in the latest version (v3.0.4).

**Comment by teyeheimans** [comment]
I am sorry, but we are not going to update version v2.x anymore.
