### ISSUE TITLE
fromDataSource doesn't exist on IndexBuilder

### ISSUE THREAD

**Issue by OpenSource03** [level23/druid-client#56]
Hello.

Looking at https://github.com/level23/druid-client?tab=readme-ov-file#reindex, I see you mentioning that there is a `fromDataSource `method on `IndexBuilder`. However, by copying the exact same code, I see that `fromDataSource `is not present in the `IndexBuilder` as seen [here](https://github.com/level23/druid-client/blob/master/src/Tasks/IndexTaskBuilder.php).

**Comment by teyeheimans** [comment]
You are totally correct. We have removed the `fromDataSource` from the README and in the example code.
